export default {
	SET_USER_EMAIL: 'SET_USER_EMAIL',
	SET_USER_PASSWORD: 'SET_USER_PASSWORD',
	USER_SIGN_UP: 'USER_SIGN_UP',
	USER_SIGN_IN: 'USER_SIGN_IN',
	USER_SIGN_OUT: 'USER_SIGN_OUT',
	GET_CURRENT_PROFILE: 'GET_CURRENT_PROFILE',
	GET_PROFILES: 'GET_PROFILES',
	CLEAR_PROFILE: 'CLEAR_PROFILE',
	START_LOAD: '_START_LOAD',
	FINISH_LOAD: '_FINISH_LOAD',
	GET_ERRORS: 'GET_ERRORS',

}